# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4f8e7c2d930f3c41700a6195310eb1c495289456da780a8a612aab81391fcd0a4713962c3295d9097d5c612557382d0f66bde7c3210a278c81668119a8798bfe

test:
  secret_key_base: 69301cac0f0b1520383cbacad80a984bfda203764c43e119f31ff8c73fb721699f717bc818b4420971869b4634de5bc173f8e2ec8be75df42fc298b0e25dafea

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
